version: '3'
services:
  react:
    build: .
    working_dir: /opt/app/client
    command: bash -c "yarn install && yarn start"  # script que faz yarn install + start
    ports:
      - 3001:3001
    stdin_open: true
    volumes:
      - ./client/:/opt/app/client
  rails:
    build: .
    command: rails s -b 0.0.0.0
    container_name: new_tasks
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    links:
      - db
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - new_tasks:/var/lib/postgresql/data
volumes:
  new_tasks: