version: '3'
services:
  react:
    build: ./client
    command: yarn start
    container_name: frontend_react
    ports:
      - 3001:3001
  rails:
    build: .
    command: rails s -b 0.0.0.0
    container_name: backend_rails
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    links:
      - db
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - backend_rails:/var/lib/postgresql/data
volumes:
  backend_rails:
  frontend_react:
