default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV.fetch("POSTGRES_HOST") %>

development:
  <<: *default
  database: TestRails_development

test:
  <<: *default
  database: TestRails_test

production:
  <<: *default
  database: TestRails_production
